CREATE TABLE IF NOT EXISTS NEM_NAMESPACE(
	C_NO INT NOT NULL PRIMARY KEY,
	C_NAME VARCHAR(128) NOT NULL,
	C_MOSAICS INT NOT NULL DEFAULT 0,
	C_TIMESTAMP BIGINT NOT NULL,
	C_HEIGHT INT NOT NULL,
	C_CREATOR VARCHAR(40)
);