CREATE TABLE IF NOT EXISTS NEM_TRANSACTION(
	C_NO INT NOT NULL PRIMARY KEY,
	C_HASH VARCHAR(64),
	C_HEIGHT INT NOT NULL,
	C_SENDER VARCHAR(40),
	C_RECIPIENT VARCHAR(40),
	C_AMOUNT LONG NOT NULL,
	C_FEE LONG NOT NULL,
	C_TIMESTAMP INT NOT NULL,
	C_DEADLINE INT NOT NULL,
	C_SIGNATURE VARCHAR(128) NOT NULL,
	C_TYPE INT NOT NULL
);

CREATE INDEX IF NOT EXISTS INDEX_NEM_TRANSACTION_C_HASH ON NEM_TRANSACTION(C_HASH);
CREATE INDEX IF NOT EXISTS INDEX_NEM_TRANSACTION_C_HEIGHT ON NEM_TRANSACTION(C_HEIGHT);
