CREATE TABLE IF NOT EXISTS NEM_SUPERNODE_PAYOUT(
	C_NO BIGINT NOT NULL PRIMARY KEY,
	C_ROUND INT NOT NULL,
	C_SENDER VARCHAR(40) NOT NULL,
	C_RECIPIENT VARCHAR(40) NOT NULL,
	C_AMOUNT BIGINT NOT NULL,
	C_FEE BIGINT NOT NULL,
	C_TIMESTAMP BIGINT NOT NULL
);